/*
 * Web UI Generation Functions
 * 
 * This file implements functions to generate HTML for the web interface
 * of the wM-Bus Gateway project.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <esp_log.h>
#include "config.h"

static const char* TAG = "WEB_UI";

/**
 * @brief Generate the main dashboard HTML
 * 
 * @return Pointer to allocated HTML string, NULL on failure
 */
char* generate_main_dashboard_html(void)
{
    const char* html_template = 
        "<!DOCTYPE html>"
        "<html>"
        "<head>"
            "<title>wM-Bus Gateway Dashboard</title>"
            "<meta charset=\"utf-8\">"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
            "<style>"
                "body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }"
                ".container { max-width: 1200px; margin: 0 auto; }"
                ".header { background-color: #4CAF50; color: white; padding: 15px; border-radius: 5px; margin-bottom: 20px; }"
                ".nav { background-color: #333; padding: 0; border-radius: 5px; margin-bottom: 20px; }"
                ".nav ul { list-style-type: none; margin: 0; padding: 0; }"
                ".nav ul li { display: inline; }"
                ".nav ul li a { color: white; padding: 14px 20px; text-decoration: none; display: inline-block; }"
                ".nav ul li a:hover { background-color: #555; }"
                ".card { background-color: white; padding: 20px; margin-bottom: 20px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }"
                ".stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; }"
                ".stat-card { background-color: #f9f9f9; padding: 15px; border-radius: 5px; text-align: center; }"
                ".stat-value { font-size: 2em; font-weight: bold; color: #4CAF50; }"
                ".stat-label { color: #666; }"
                ".connection-status { display: flex; align-items: center; }"
                ".status-indicator { width: 12px; height: 12px; border-radius: 50%%; margin-right: 10px; }"
                ".connected { background-color: #4CAF50; }"
                ".disconnected { background-color: #f44336; }"
                ".device-table { width: 100%%; border-collapse: collapse; }"
                ".device-table th, .device-table td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }"
                ".device-table th { background-color: #f2f2f2; }"
            "</style>"
        "</head>"
        "<body>"
            "<div class=\"container\">"
                "<div class=\"header\">"
                    "<h1>wM-Bus Gateway Dashboard</h1>"
                    "<p>Monitor and configure your wM-Bus device</p>"
                "</div>"
                
                "<div class=\"nav\">"
                    "<ul>"
                        "<li><a href=\"/\">Dashboard</a></li>"
                        "<li><a href=\"/wifi\">WiFi Config</a></li>"
                        "<li><a href=\"/whitelist\">Whitelist</a></li>"
                        "<li><a href=\"/radio\">Radio Settings</a></li>"
                        "<li><a href=\"/backend\">Backend</a></li>"
                    "</ul>"
                "</div>"
                
                "<div class=\"card\">"
                    "<h2>Connection Status</h2>"
                    "<div class=\"connection-status\">"
                        "<div class=\"status-indicator connected\" id=\"wifi-status\"></div>"
                        "<span>WiFi: <span id=\"wifi-status-text\">Connected</span></span>"
                    "</div>"
                    "<div class=\"connection-status\" style=\"margin-top: 10px;\">"
                        "<div class=\"status-indicator connected\" id=\"backend-status\"></div>"
                        "<span>Backend: <span id=\"backend-status-text\">Connected</span></span>"
                    "</div>"
                    "<div class=\"connection-status\" style=\"margin-top: 10px;\">"
                        "<div class=\"status-indicator disconnected\" id=\"radio-status\"></div>"
                        "<span>Radio: <span id=\"radio-status-text\">Checking...</span></span>"
                    "</div>"
                "</div>"
                
                "<div class=\"card\">"
                    "<h2>Packet Statistics</h2>"
                    "<div class=\"stats-grid\">"
                        "<div class=\"stat-card\">"
                            "<div class=\"stat-value\" id=\"total-packets\">0</div>"
                            "<div class=\"stat-label\">Total Packets</div>"
                        "</div>"
                        "<div class=\"stat-card\">"
                            "<div class=\"stat-value\" id=\"forwarded-packets\">0</div>"
                            "<div class=\"stat-label\">Forwarded Packets</div>"
                        "</div>"
                        "<div class=\"stat-card\">"
                            "<div class=\"stat-value\" id=\"detected-devices\">0</div>"
                            "<div class=\"stat-label\">Detected Devices</div>"
                        "</div>"
                    "</div>"
                "</div>"
                
                "<div class=\"card\">"
                    "<h2>Detected Devices</h2>"
                    "<table class=\"device-table\">"
                        "<thead>"
                            "<tr>"
                                "<th>Device Address</th>"
                                "<th>Type</th>"
                                "<th>Signal Strength (dBm)</th>"
                                "<th>Last Seen</th>"
                            "</tr>"
                        "</thead>"
                        "<tbody id=\"devices-list\">"
                            "<tr><td colspan=\"4\">Loading...</td></tr>"
                        "</tbody>"
                    "</table>"
                "</div>"
            "</div>"
            
            "<script>"
                "function updateDashboard() {"
                    "fetch('/api/dashboard_stats')"
                    ".then(response => response.json())"
                    ".then(data => {"
                        "document.getElementById('total-packets').textContent = data.total_packets;"
                        "document.getElementById('forwarded-packets').textContent = data.forwarded_packets;"
                        "document.getElementById('detected-devices').textContent = data.detected_devices;"
                        
                        "// Update connection status indicators"
                        "const wifiStatus = document.getElementById('wifi-status');"
                        "const wifiStatusText = document.getElementById('wifi-status-text');"
                        "const wifiInfo = data.connection_status && data.connection_status.wifi;"
                        "if (wifiInfo && wifiInfo.status === 'running') {"
                            "wifiStatus.className = 'status-indicator connected';"
                        "} else {"
                            "wifiStatus.className = 'status-indicator disconnected';"
                        "}"
                        "if (wifiInfo) {"
                            "if (wifiInfo.mode === 'AP') {"
                                "wifiStatusText.textContent = `AP Mode (${wifiInfo.ssid})`;"
                            "} else if (wifiInfo.status === 'connected') {"
                                "wifiStatusText.textContent = `Connected to ${wifiInfo.ssid}`;"
                            "} else {"
                                "wifiStatusText.textContent = 'Disconnected';"
                            "}"
                        "} else {"
                            "wifiStatusText.textContent = 'Unknown';"
                        "}"

                        "const backendStatus = document.getElementById('backend-status');"
                        "const backendStatusText = document.getElementById('backend-status-text');"
                        "const backendInfo = data.connection_status && data.connection_status.backend;"
                        "if (backendInfo && backendInfo.configured) {"
                            "if (backendInfo.status === 'success') {"
                                "backendStatus.className = 'status-indicator connected';"
                                "backendStatusText.textContent = `Connected (${backendInfo.url})`;"
                            "} else {"
                                "backendStatus.className = 'status-indicator disconnected';"
                                "backendStatusText.textContent = backendInfo.message || 'Configured (untested)';"
                            "}"
                        "} else {"
                            "backendStatus.className = 'status-indicator disconnected';"
                            "backendStatusText.textContent = 'Not configured';"
                        "}"

                        "const radioStatus = document.getElementById('radio-status');"
                        "const radioStatusText = document.getElementById('radio-status-text');"
                        "const radioInfo = data.connection_status && data.connection_status.radio;"
                        "if (radioInfo) {"
                            "radioStatus.className = radioInfo.available ? 'status-indicator connected' : 'status-indicator disconnected';"
                            "radioStatusText.textContent = radioInfo.message || (radioInfo.available ? 'Ready' : 'Unavailable');"
                        "} else {"
                            "radioStatus.className = 'status-indicator disconnected';"
                            "radioStatusText.textContent = 'Unknown';"
                        "}"
                    "})"
                    ".catch(error => console.error('Error fetching dashboard stats:', error));"
                    
                    "fetch('/api/detected_devices')"
                    ".then(response => response.json())"
                    ".then(devices => {"
                        "const devicesList = document.getElementById('devices-list');"
                        "devicesList.innerHTML = '';"
                        
                        "devices.forEach(device => {"
                            "const row = document.createElement('tr');"
                            "row.innerHTML = "
                                "'<td>' + device.address + '</td>' +"
                                "'<td>' + device.type + '</td>' +"
                                "'<td>' + device.rssi + '</td>' +"
                                "'<td>' + device.last_seen + '</td>';"
                            "devicesList.appendChild(row);"
                        "});"
                    "})"
                    ".catch(error => console.error('Error fetching detected devices:', error));"
                "}"
                
                "// Update dashboard every 5 seconds"
                "updateDashboard();"
                "setInterval(updateDashboard, 5000);"
            "</script>"
        "</body>"
        "</html>";

    char* result = malloc(strlen(html_template) + 1);
    if (!result) {
        ESP_LOGE(TAG, "Failed to allocate memory for dashboard HTML");
        return NULL;
    }
    strcpy(result, html_template);
    return result;
}

/**
 * @brief Generate the WiFi configuration HTML
 * 
 * @return Pointer to allocated HTML string, NULL on failure
 */
char* generate_wifi_config_html(void)
{
    const char* html_template = 
        "<!DOCTYPE html>"
        "<html>"
        "<head>"
            "<title>WiFi Configuration - wM-Bus Gateway</title>"
            "<meta charset=\"utf-8\">"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
            "<style>"
                "body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }"
                ".container { max-width: 800px; margin: 0 auto; }"
                ".header { background-color: #4CAF50; color: white; padding: 15px; border-radius: 5px; margin-bottom: 20px; }"
                ".nav { background-color: #333; padding: 0; border-radius: 5px; margin-bottom: 20px; }"
                ".nav ul { list-style-type: none; margin: 0; padding: 0; }"
                ".nav ul li { display: inline; }"
                ".nav ul li a { color: white; padding: 14px 20px; text-decoration: none; display: inline-block; }"
                ".nav ul li a:hover { background-color: #555; }"
                ".card { background-color: white; padding: 20px; margin-bottom: 20px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }"
                "label { display: block; margin-bottom: 8px; font-weight: bold; }"
                "input[type='text'], input[type='password'] { width: 100%%; padding: 10px; margin-bottom: 15px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; }"
                "button { background-color: #4CAF50; color: white; padding: 12px 20px; border: none; border-radius: 4px; cursor: pointer; }"
                "button:hover { background-color: #45a049; }"
                ".status { margin-top: 15px; padding: 10px; border-radius: 4px; }"
                ".success { background-color: #d4edda; color: #155724; border: 1px solid #c3e6cb; }"
                ".error { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }"
            "</style>"
        "</head>"
        "<body>"
            "<div class=\"container\">"
                "<div class=\"header\">"
                    "<h1>WiFi Configuration</h1>"
                    "<p>Configure your wM-Bus Gateway's WiFi connection</p>"
                "</div>"
                
                "<div class=\"nav\">"
                    "<ul>"
                        "<li><a href=\"/\">Dashboard</a></li>"
                        "<li><a href=\"/wifi\">WiFi Config</a></li>"
                        "<li><a href=\"/whitelist\">Whitelist</a></li>"
                        "<li><a href=\"/radio\">Radio Settings</a></li>"
                        "<li><a href=\"/backend\">Backend</a></li>"
                    "</ul>"
                "</div>"
                
                "<div class=\"card\">"
                    "<h2>Connect to WiFi Network</h2>"
                    "<form id=\"wifi-form\">"
                        "<label for=\"ssid\">WiFi Network (SSID):</label>"
                        "<input type=\"text\" id=\"ssid\" name=\"ssid\" required>"
                        
                        "<label for=\"password\">Password:</label>"
                        "<input type=\"password\" id=\"password\" name=\"password\" required>"
                        
                        "<button type=\"submit\">Save WiFi Credentials</button>"
                    "</form>"
                    
                    "<div id=\"status\" class=\"status\" style=\"display: none;\"></div>"
                "</div>"
                
                "<div class=\"card\">"
                    "<h2>Current Connection Status</h2>"
                    "<div class=\"connection-status\">"
                        "<div class=\"status-indicator\" id=\"wifi-status\"></div>"
                        "<span>Status: <span id=\"wifi-status-text\">Checking...</span></span>"
                    "</div>"
                    "<div id=\"connection-details\" style=\"margin-top: 10px;\"></div>"
                "</div>"
            "</div>"
            
            "<script>"
                "document.getElementById('wifi-form').addEventListener('submit', function(e) {"
                    "e.preventDefault();"
                    
                    "const ssid = document.getElementById('ssid').value;"
                    "const password = document.getElementById('password').value;"
                    
                    "const formData = `ssid=${encodeURIComponent(ssid)}&password=${encodeURIComponent(password)}`;"
                    
                    "fetch('/wifi', {"
                        "method: 'POST',"
                        "headers: {"
                            "'Content-Type': 'application/x-www-form-urlencoded',"
                        "},"
                        "body: formData"
                    "})"
                    ".then(response => response.json())"
                    ".then(data => {"
                        "const statusDiv = document.getElementById('status');"
                        "statusDiv.style.display = 'block';"
                        "if (data.status === 'success') {"
                            "statusDiv.className = 'status success';"
                            "statusDiv.textContent = data.message;"
                        "} else {"
                            "statusDiv.className = 'status error';"
                            "statusDiv.textContent = 'Error: ' + (data.message || 'Unknown error');"
                        "}"
                    "})"
                    ".catch(error => {"
                        "const statusDiv = document.getElementById('status');"
                        "statusDiv.style.display = 'block';"
                        "statusDiv.className = 'status error';"
                        "statusDiv.textContent = 'Error: ' + error.message;"
                    "});"
                "});"
                
                "function updateWifiStatus() {"
                    "fetch('/api/wifi_status')"
                    ".then(response => response.json())"
                    ".then(data => {"
                        "const statusIndicator = document.getElementById('wifi-status');"
                        "const statusText = document.getElementById('wifi-status-text');"
                        "const detailsDiv = document.getElementById('connection-details');"
                        "const wifiInfo = data;"
                        "if (wifiInfo && wifiInfo.status === 'running') {"
                            "statusIndicator.style.backgroundColor = '#4CAF50';"
                        "} else {"
                            "statusIndicator.style.backgroundColor = '#f44336';"
                        "}"
                        "if (wifiInfo) {"
                            "if (wifiInfo.mode === 'AP') {"
                                "statusText.textContent = `AP Mode (${wifiInfo.ssid})`;"
                            "} else if (wifiInfo.status === 'connected') {"
                                "statusText.textContent = `Connected to ${wifiInfo.ssid}`;"
                            "} else {"
                                "statusText.textContent = 'Disconnected';"
                            "}"
                            "detailsDiv.innerHTML = '<p>Network: ' + (wifiInfo.ssid || 'n/a') + '</p>' +"
                                "'<p>Channel: ' + (wifiInfo.channel || 'n/a') + '</p>' +"
                                "'<p>Signal: ' + (wifiInfo.rssi || 0) + ' dBm</p>';"
                        "} else {"
                            "statusText.textContent = 'Unknown';"
                            "detailsDiv.innerHTML = '<p>Unable to read WiFi status</p>';"
                        "}"
                    "})"
                    ".catch(error => console.error('Error fetching WiFi status:', error));"
                "}"
                "// Update WiFi status every 5 seconds"
                "updateWifiStatus();"
                "setInterval(updateWifiStatus, 5000);"
            "</script>"
        "</body>"
        "</html>";

    char* result = malloc(strlen(html_template) + 1);
    if (!result) {
        ESP_LOGE(TAG, "Failed to allocate memory for WiFi config HTML");
        return NULL;
    }
    strcpy(result, html_template);
    return result;
}

/**
 * @brief Generate the whitelist management HTML
 * 
 * @return Pointer to allocated HTML string, NULL on failure
 */
char* generate_whitelist_html(void)
{
    const char* html_template = 
        "<!DOCTYPE html>"
        "<html>"
        "<head>"
            "<title>Whitelist Management - wM-Bus Gateway</title>"
            "<meta charset=\"utf-8\">"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
            "<style>"
                "body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }"
                ".container { max-width: 1000px; margin: 0 auto; }"
                ".header { background-color: #4CAF50; color: white; padding: 15px; border-radius: 5px; margin-bottom: 20px; }"
                ".nav { background-color: #333; padding: 0; border-radius: 5px; margin-bottom: 20px; }"
                ".nav ul { list-style-type: none; margin: 0; padding: 0; }"
                ".nav ul li { display: inline; }"
                ".nav ul li a { color: white; padding: 14px 20px; text-decoration: none; display: inline-block; }"
                ".nav ul li a:hover { background-color: #555; }"
                ".card { background-color: white; padding: 20px; margin-bottom: 20px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }"
                "label { display: block; margin-bottom: 8px; font-weight: bold; }"
                "input[type='text'] { width: 100%%; padding: 10px; margin-bottom: 15px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; }"
                "button { background-color: #4CAF50; color: white; padding: 10px 15px; border: none; border-radius: 4px; cursor: pointer; margin-right: 10px; }"
                "button:hover { background-color: #45a049; }"
                "button.remove { background-color: #f44336; }"
                "button.remove:hover { background-color: #da190b; }"
                ".whitelist-table { width: 100%%; border-collapse: collapse; }"
                ".whitelist-table th, .whitelist-table td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }"
                ".whitelist-table th { background-color: #f2f2f2; }"
                ".status { margin-top: 15px; padding: 10px; border-radius: 4px; }"
                ".success { background-color: #d4edda; color: #155724; border: 1px solid #c3e6cb; }"
                ".error { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }"
            "</style>"
        "</head>"
        "<body>"
            "<div class=\"container\">"
                "<div class=\"header\">"
                    "<h1>Whitelist Management</h1>"
                    "<p>Manage which wM-Bus devices are allowed to forward data</p>"
                "</div>"
                
                "<div class=\"nav\">"
                    "<ul>"
                        "<li><a href=\"/\">Dashboard</a></li>"
                        "<li><a href=\"/wifi\">WiFi Config</a></li>"
                        "<li><a href=\"/whitelist\">Whitelist</a></li>"
                        "<li><a href=\"/radio\">Radio Settings</a></li>"
                        "<li><a href=\"/backend\">Backend</a></li>"
                    "</ul>"
                "</div>"
                
                "<div class=\"card\">"
                    "<h2>Add Device to Whitelist</h2>"
                    "<form id=\"add-device-form\">"
                        "<label for=\"device-address\">Device Address (16-character hex):</label>"
                        "<input type=\"text\" id=\"device-address\" name=\"device_address\" placeholder=\"e.g., 12345678AABBCCDD\" required maxlength=\"16\">"
                        
                        "<button type=\"submit\">Add to Whitelist</button>"
                    "</form>"
                    
                    "<div id=\"status\" class=\"status\" style=\"display: none;\"></div>"
                "</div>"
                
                "<div class=\"card\">"
                    "<h2>Current Whitelist</h2>"
                    "<table class=\"whitelist-table\">"
                        "<thead>"
                            "<tr>"
                                "<th>Device Address</th>"
                                "<th>Device Type</th>"
                                "<th>Added Date</th>"
                                "<th>Action</th>"
                            "</tr>"
                        "</thead>"
                        "<tbody id=\"whitelist-table-body\">"
                            "<tr><td colspan=\"4\">Loading...</td></tr>"
                        "</tbody>"
                    "</table>"
                "</div>"
            "</div>"
            
            "<script>"
                "document.getElementById('add-device-form').addEventListener('submit', function(e) {"
                    "e.preventDefault();"
                    
                    "const deviceAddress = document.getElementById('device-address').value;"
                    
                    "const formData = `device_address=${encodeURIComponent(deviceAddress)}&action=1`;"
                    
                    "fetch('/whitelist', {"
                        "method: 'POST',"
                        "headers: {"
                            "'Content-Type': 'application/x-www-form-urlencoded',"
                        "},"
                        "body: formData"
                    "})"
                    ".then(response => response.json())"
                    ".then(data => {"
                        "const statusDiv = document.getElementById('status');"
                        "statusDiv.style.display = 'block';"
                        "if (data.status === 'success') {"
                            "statusDiv.className = 'status success';"
                            "statusDiv.textContent = data.message;"
                            "document.getElementById('device-address').value = ''; // Clear the input"
                            "updateWhitelist(); // Refresh the whitelist"
                        "} else {"
                            "statusDiv.className = 'status error';"
                            "statusDiv.textContent = 'Error: ' + (data.message || 'Unknown error');"
                        "}"
                    "})"
                    ".catch(error => {"
                        "const statusDiv = document.getElementById('status');"
                        "statusDiv.style.display = 'block';"
                        "statusDiv.className = 'status error';"
                        "statusDiv.textContent = 'Error: ' + error.message;"
                    "});"
                "});"
                
                "function removeFromWhitelist(deviceAddress) {"
                    "if (!confirm('Are you sure you want to remove this device from the whitelist?')) {"
                        "return;"
                    "}"
                    
                    "const formData = `device_address=${encodeURIComponent(deviceAddress)}&action=0`;"
                    
                    "fetch('/whitelist', {"
                        "method: 'POST',"
                        "headers: {"
                            "'Content-Type': 'application/x-www-form-urlencoded',"
                        "},"
                        "body: formData"
                    "})"
                    ".then(response => response.json())"
                    ".then(data => {"
                        "const statusDiv = document.getElementById('status');"
                        "statusDiv.style.display = 'block';"
                        "if (data.status === 'success') {"
                            "statusDiv.className = 'status success';"
                            "statusDiv.textContent = data.message;"
                            "updateWhitelist(); // Refresh the whitelist"
                        "} else {"
                            "statusDiv.className = 'status error';"
                            "statusDiv.textContent = 'Error: ' + (data.message || 'Unknown error');"
                        "}"
                    "})"
                    ".catch(error => {"
                        "const statusDiv = document.getElementById('status');"
                        "statusDiv.style.display = 'block';"
                        "statusDiv.className = 'status error';"
                        "statusDiv.textContent = 'Error: ' + error.message;"
                    "});"
                "}"
                
                "function updateWhitelist() {"
                    "fetch('/api/whitelist')"
                    ".then(response => response.json())"
                    ".then(devices => {"
                        "const tableBody = document.getElementById('whitelist-table-body');"
                        "tableBody.innerHTML = '';"
                        
                        "if (devices.length === 0) {"
                            "const row = document.createElement('tr');"
                            "row.innerHTML = '<td colspan=\"4\">No devices in whitelist</td>';"
                            "tableBody.appendChild(row);"
                            "return;"
                        "}"
                        
                        "devices.forEach(device => {"
                            "const row = document.createElement('tr');"
                            "row.innerHTML = "
                                "'<td>' + device + '</td>' +"
                                "'<td>Unknown</td>' +"
                                "'<td>2023-01-01</td>' +"
                                "'<td><button class=\"remove\" onclick=\"removeFromWhitelist(\\'' + device + '\\')\">Remove</button></td>';"
                            "tableBody.appendChild(row);"
                        "});"
                    "})"
                    ".catch(error => console.error('Error fetching whitelist:', error));"
                "}"
                
                "// Initial load of the whitelist"
                "updateWhitelist();"
            "</script>"
        "</body>"
        "</html>";

    char* result = malloc(strlen(html_template) + 1);
    if (!result) {
        ESP_LOGE(TAG, "Failed to allocate memory for whitelist HTML");
        return NULL;
    }
    strcpy(result, html_template);
    return result;
}

/**
 * @brief Generate the radio settings HTML
 * 
 * @return Pointer to allocated HTML string, NULL on failure
 */
char* generate_radio_settings_html(void)
{
    const char* html_template = 
        "<!DOCTYPE html>"
        "<html>"
        "<head>"
            "<title>Radio Settings - wM-Bus Gateway</title>"
            "<meta charset=\"utf-8\">"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
            "<style>"
                "body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }"
                ".container { max-width: 800px; margin: 0 auto; }"
                ".header { background-color: #4CAF50; color: white; padding: 15px; border-radius: 5px; margin-bottom: 20px; }"
                ".nav { background-color: #333; padding: 0; border-radius: 5px; margin-bottom: 20px; }"
                ".nav ul { list-style-type: none; margin: 0; padding: 0; }"
                ".nav ul li { display: inline; }"
                ".nav ul li a { color: white; padding: 14px 20px; text-decoration: none; display: inline-block; }"
                ".nav ul li a:hover { background-color: #555; }"
                ".card { background-color: white; padding: 20px; margin-bottom: 20px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }"
                "label { display: block; margin-bottom: 8px; font-weight: bold; }"
                "input[type='number'], input[type='range'] { width: 100%%; padding: 8px; margin-bottom: 15px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; }"
                "input[type='checkbox'] { margin-right: 8px; }"
                ".form-group { margin-bottom: 20px; }"
                ".range-container { display: flex; align-items: center; }"
                ".range-container input[type='range'] { flex: 1; margin-right: 15px; }"
                ".range-value { width: 60px; text-align: center; }"
                "button { background-color: #4CAF50; color: white; padding: 12px 20px; border: none; border-radius: 4px; cursor: pointer; }"
                "button:hover { background-color: #45a049; }"
                ".status { margin-top: 15px; padding: 10px; border-radius: 4px; }"
                ".success { background-color: #d4edda; color: #155724; border: 1px solid #c3e6cb; }"
                ".error { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }"
            "</style>"
        "</head>"
        "<body>"
            "<div class=\"container\">"
                "<div class=\"header\">"
                    "<h1>Radio Settings</h1>"
                    "<p>Configure wM-Bus radio parameters and noise filtering</p>"
                "</div>"
                
                "<div class=\"nav\">"
                    "<ul>"
                        "<li><a href=\"/\">Dashboard</a></li>"
                        "<li><a href=\"/wifi\">WiFi Config</a></li>"
                        "<li><a href=\"/whitelist\">Whitelist</a></li>"
                        "<li><a href=\"/radio\">Radio Settings</a></li>"
                        "<li><a href=\"/backend\">Backend</a></li>"
                    "</ul>"
                "</div>"
                
                "<div class=\"card\">"
                    "<h2>Radio Configuration</h2>"
                    "<form id=\"radio-settings-form\">"
                        "<div class=\"form-group\">"
                            "<label for=\"frequency\">Frequency (MHz):</label>"
                            "<input type=\"number\" id=\"frequency\" name=\"frequency\" step=\"0.1\" min=\"868.0\" max=\"868.6\" value=\"868.3\">"
                        "</div>"
                        
                        "<div class=\"form-group\">"
                            "<label for=\"data-rate\">Data Rate (bps):</label>"
                            "<input type=\"number\" id=\"data-rate\" name=\"data_rate\" min=\"300\" max=\"100000\" value=\"32768\">"
                        "</div>"
                        
                        "<div class=\"form-group\">"
                            "<label>Signal Strength Threshold (dBm):</label>"
                            "<div class=\"range-container\">"
                                "<input type=\"range\" id=\"signal-threshold\" name=\"signal_threshold\" min=\"-100\" max=\"-20\" value=\"-80\">"
                                "<input type=\"number\" id=\"signal-threshold-value\" value=\"-80\" readonly style=\"width: 80px;\">"
                            "</div>"
                        "</div>"
                        
                        "<div class=\"form-group\">"
                            "<label>Sync Quality Threshold:</label>"
                            "<div class=\"range-container\">"
                                "<input type=\"range\" id=\"sync-quality\" name=\"sync_quality_threshold\" min=\"0\" max=\"1\" step=\"0.01\" value=\"0.7\">"
                                "<input type=\"number\" id=\"sync-quality-value\" value=\"0.7\" readonly style=\"width: 80px;\">"
                            "</div>"
                        "</div>"
                        
                        "<div class=\"form-group\">"
                            "<label>"
                                "<input type=\"checkbox\" id=\"agc-enabled\" name=\"agc_enabled\" checked>"
                                "Enable Automatic Gain Control (AGC)"
                            "</label>"
                        "</div>"
                        
                        "<button type=\"submit\">Save Radio Settings</button>"
                    "</form>"
                    
                    "<div id=\"status\" class=\"status\" style=\"display: none;\"></div>"
                "</div>"
                
                "<div class=\"card\">"
                    "<h2>Radio Hardware Status</h2>"
                    "<div class=\"connection-status\">"
                        "<div class=\"status-indicator\" id=\"radio-status-panel\"></div>"
                        "<span>Status: <span id=\"radio-status-text-panel\">Checking...</span></span>"
                    "</div>"
                    "<div id=\"radio-status-message\" style=\"margin-top: 10px;\"></div>"
                "</div>"
            "</div>"
            
            "<script>"
                "// Update range value displays"
                "document.getElementById('signal-threshold').addEventListener('input', function() {"
                    "document.getElementById('signal-threshold-value').value = this.value;"
                "});"
                
                "document.getElementById('sync-quality').addEventListener('input', function() {"
                    "document.getElementById('sync-quality-value').value = this.value;"
                "});"
                
                "document.getElementById('radio-settings-form').addEventListener('submit', function(e) {"
                    "e.preventDefault();"
                    
                    "const settings = {"
                        "frequency: parseFloat(document.getElementById('frequency').value),"
                        "data_rate: parseInt(document.getElementById('data-rate').value),"
                        "signal_threshold: parseInt(document.getElementById('signal-threshold').value),"
                        "sync_quality_threshold: parseFloat(document.getElementById('sync-quality').value),"
                        "agc_enabled: document.getElementById('agc-enabled').checked"
                    "};"
                    
                    "fetch('/api/radio', {"
                        "method: 'POST',"
                        "headers: {"
                            "'Content-Type': 'application/json',"
                        "},"
                        "body: JSON.stringify(settings)"
                    "})"
                    ".then(response => response.json())"
                    ".then(data => {"
                        "const statusDiv = document.getElementById('status');"
                        "statusDiv.style.display = 'block';"
                        "if (data.status === 'success') {"
                            "statusDiv.className = 'status success';"
                            "statusDiv.textContent = data.message;"
                        "} else {"
                            "statusDiv.className = 'status error';"
                            "statusDiv.textContent = 'Error: ' + (data.message || 'Unknown error');"
                        "}"
                    "})"
                    ".catch(error => {"
                        "const statusDiv = document.getElementById('status');"
                        "statusDiv.style.display = 'block';"
                        "statusDiv.className = 'status error';"
                        "statusDiv.textContent = 'Error: ' + error.message;"
                    "});"
                "});"
                
                "// Load current settings"
                "fetch('/api/radio')"
                ".then(response => response.json())"
                ".then(settings => {"
                    "document.getElementById('frequency').value = settings.frequency;"
                    "document.getElementById('data-rate').value = settings.data_rate;"
                    "document.getElementById('signal-threshold').value = settings.signal_threshold;"
                    "document.getElementById('signal-threshold-value').value = settings.signal_threshold;"
                    "document.getElementById('sync-quality').value = settings.sync_quality_threshold;"
                    "document.getElementById('sync-quality-value').value = settings.sync_quality_threshold;"
                    "document.getElementById('agc-enabled').checked = settings.agc_enabled;"
                "})"
                ".catch(error => console.error('Error fetching radio settings:', error));"

                "function updateRadioStatusPanel() {"
                    "fetch('/api/dashboard_stats')"
                    ".then(response => response.json())"
                    ".then(data => {"
                        "const radioInfo = data.connection_status && data.connection_status.radio;"
                        "const indicator = document.getElementById('radio-status-panel');"
                        "const text = document.getElementById('radio-status-text-panel');"
                        "const message = document.getElementById('radio-status-message');"
                        "if (radioInfo) {"
                            "indicator.className = radioInfo.available ? 'status-indicator connected' : 'status-indicator disconnected';"
                            "text.textContent = radioInfo.message || (radioInfo.available ? 'Ready' : 'Unavailable');"
                            "message.textContent = radioInfo.message || '';"
                        "} else {"
                            "indicator.className = 'status-indicator disconnected';"
                            "text.textContent = 'Unknown';"
                            "message.textContent = 'Unable to retrieve radio status';"
                        "}"
                    "})"
                    ".catch(error => console.error('Error fetching radio status:', error));"
                "}"

                "updateRadioStatusPanel();"
                "setInterval(updateRadioStatusPanel, 5000);"
            "</script>"
        "</body>"
        "</html>";

    char* result = malloc(strlen(html_template) + 1);
    if (!result) {
        ESP_LOGE(TAG, "Failed to allocate memory for radio settings HTML");
        return NULL;
    }
    strcpy(result, html_template);
    return result;
}

/**
 * @brief Generate the backend settings HTML
 * 
 * @return Pointer to allocated HTML string, NULL on failure
 */
char* generate_backend_settings_html(void)
{
    const char* html_template = 
        "<!DOCTYPE html>"
        "<html>"
        "<head>"
            "<title>Backend Settings - wM-Bus Gateway</title>"
            "<meta charset=\"utf-8\">"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
            "<style>"
                "body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }"
                ".container { max-width: 800px; margin: 0 auto; }"
                ".header { background-color: #4CAF50; color: white; padding: 15px; border-radius: 5px; margin-bottom: 20px; }"
                ".nav { background-color: #333; padding: 0; border-radius: 5px; margin-bottom: 20px; }"
                ".nav ul { list-style-type: none; margin: 0; padding: 0; }"
                ".nav ul li { display: inline; }"
                ".nav ul li a { color: white; padding: 14px 20px; text-decoration: none; display: inline-block; }"
                ".nav ul li a:hover { background-color: #555; }"
                ".card { background-color: white; padding: 20px; margin-bottom: 20px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }"
                "label { display: block; margin-bottom: 8px; font-weight: bold; }"
                "input[type='text'], input[type='password'], input[type='number'] { width: 100%%; padding: 10px; margin-bottom: 15px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; }"
                "button { background-color: #4CAF50; color: white; padding: 12px 20px; border: none; border-radius: 4px; cursor: pointer; margin-right: 10px; }"
                "button:hover { background-color: #45a049; }"
                "button.test { background-color: #2196F3; }"
                "button.test:hover { background-color: #0b7dda; }"
                ".status { margin-top: 15px; padding: 10px; border-radius: 4px; }"
                ".success { background-color: #d4edda; color: #155724; border: 1px solid #c3e6cb; }"
                ".error { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }"
                ".connection-status { display: flex; align-items: center; margin-top: 10px; }"
                ".status-indicator { width: 12px; height: 12px; border-radius: 50%%; margin-right: 10px; }"
                ".connected { background-color: #4CAF50; }"
                ".disconnected { background-color: #f44336; }"
            "</style>"
        "</head>"
        "<body>"
            "<div class=\"container\">"
                "<div class=\"header\">"
                    "<h1>Backend Settings</h1>"
                    "<p>Configure connection to your backend server</p>"
                "</div>"
                
                "<div class=\"nav\">"
                    "<ul>"
                        "<li><a href=\"/\">Dashboard</a></li>"
                        "<li><a href=\"/wifi\">WiFi Config</a></li>"
                        "<li><a href=\"/whitelist\">Whitelist</a></li>"
                        "<li><a href=\"/radio\">Radio Settings</a></li>"
                        "<li><a href=\"/backend\">Backend</a></li>"
                    "</ul>"
                "</div>"
                
                "<div class=\"card\">"
                    "<h2>Backend Configuration</h2>"
                    "<form id=\"backend-settings-form\">"
                        "<label for=\"server-url\">Backend Server URL:</label>"
                        "<input type=\"text\" id=\"server-url\" name=\"server_url\" placeholder=\"e.g., https://api.example.com/data\" required>"
                        
                        "<label for=\"api-key\">API Key (if required):</label>"
                        "<input type=\"password\" id=\"api-key\" name=\"api_key\" placeholder=\"Enter your API key\">"
                        
                        "<label for=\"port\">Port (if different from default):</label>"
                        "<input type=\"number\" id=\"port\" name=\"port\" placeholder=\"e.g., 80 or 443\" min=\"1\" max=\"65535\">"
                        
                        "<button type=\"submit\">Save Backend Settings</button>"
                        "<button type=\"button\" class=\"test\" id=\"test-connection\">Test Connection</button>"
                    "</form>"
                    
                    "<div class=\"connection-status\">"
                        "<div class=\"status-indicator\" id=\"backend-status\"></div>"
                        "<span>Connection: <span id=\"backend-status-text\">Checking...</span></span>"
                    "</div>"
                    
                    "<div id=\"status\" class=\"status\" style=\"display: none;\"></div>"
                "</div>"
            "</div>"
            
            "<script>"
                "const statusDiv = document.getElementById('status');"
                "const backendIndicator = document.getElementById('backend-status');"
                "const backendText = document.getElementById('backend-status-text');"
                "const serverUrlInput = document.getElementById('server-url');"
                "const apiKeyInput = document.getElementById('api-key');"
                "const portInput = document.getElementById('port');"
                "function setStatusMessage(message, type) {"
                    "statusDiv.style.display = 'block';"
                    "statusDiv.className = type ? `status ${type}` : 'status';"
                    "statusDiv.textContent = message;"
                "}"
                "function renderBackendStatus(info) {"
                    "if (!info || !info.configured) {"
                        "backendIndicator.className = 'status-indicator disconnected';"
                        "backendText.textContent = 'Not configured';"
                        "return;"
                    "}"
                    "if (info.status === 'success') {"
                        "backendIndicator.className = 'status-indicator connected';"
                        "backendText.textContent = `Connected (${info.url})`;"
                    "} else {"
                        "backendIndicator.className = 'status-indicator disconnected';"
                        "backendText.textContent = info.message || 'Configured (untested)';"
                    "}"
                "}"
                "function refreshBackendStatus() {"
                    "fetch('/api/backend_status')"
                    ".then(response => response.json())"
                    ".then(info => {"
                        "serverUrlInput.value = info.url || '';"
                        "statusDiv.style.display = 'none';"
                        "renderBackendStatus(info);"
                    "})"
                    ".catch(error => {"
                        "renderBackendStatus(null);"
                        "setStatusMessage('Unable to load backend status', 'error');"
                    "});"
                "}"
                "document.getElementById('backend-settings-form').addEventListener('submit', function(e) {"
                    "e.preventDefault();"
                    "const serverUrl = serverUrlInput.value.trim();"
                    "if (!serverUrl) {"
                        "setStatusMessage('Provide a backend URL before saving', 'error');"
                        "return;"
                    "}"
                    "const payload = { server_url: serverUrl };"
                    "const apiKey = apiKeyInput.value.trim();"
                    "const portValue = portInput.value.trim();"
                    "if (apiKey) { payload.api_key = apiKey; }"
                    "if (portValue) { payload.port = Number(portValue); }"
                    "fetch('/api/backend', {"
                        "method: 'POST',"
                        "headers: { 'Content-Type': 'application/json' },"
                        "body: JSON.stringify(payload)"
                    "})"
                    ".then(response => response.json())"
                    ".then(result => {"
                        "setStatusMessage(result.message || 'Settings saved', result.status === 'success' ? 'success' : 'error');"
                        "refreshBackendStatus();"
                    "})"
                    ".catch(error => setStatusMessage('Save failed: ' + error.message, 'error'));"
                "});"
                "document.getElementById('test-connection').addEventListener('click', function() {"
                    "const serverUrl = serverUrlInput.value.trim();"
                    "if (!serverUrl) {"
                        "setStatusMessage('Provide a backend URL before testing', 'error');"
                        "return;"
                    "}"
                    "setStatusMessage('Testing connection...', '');"
                    "fetch('/api/backend/test', {"
                        "method: 'POST',"
                        "headers: { 'Content-Type': 'application/json' },"
                        "body: JSON.stringify({ server_url: serverUrl })"
                    "})"
                    ".then(response => response.json())"
                    ".then(result => {"
                        "setStatusMessage(result.message || 'Test completed', result.status === 'success' ? 'success' : 'error');"
                        "refreshBackendStatus();"
                    "})"
                    ".catch(error => setStatusMessage('Test failed: ' + error.message, 'error'));"
                "});"
                "refreshBackendStatus();"
            "</script>"
        "</body>"
        "</html>";

    char* result = malloc(strlen(html_template) + 1);
    if (!result) {
        ESP_LOGE(TAG, "Failed to allocate memory for backend settings HTML");
        return NULL;
    }
    strcpy(result, html_template);
    return result;
}
